/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AutomationTemplatesRouteImport } from './routes/automation-templates'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExecutionJobsRouteImport } from './routes/execution-jobs'
import { Route as ExecutionPlansRouteImport } from './routes/execution-plans'
import { Route as FilesRouteImport } from './routes/files'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StorageConnectionsRouteImport } from './routes/storage-connections'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as WorkflowExecutionsRouteImport } from './routes/workflow-executions'
import { Route as WorkflowPoliciesRouteImport } from './routes/workflow-policies'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as ExecutionJobsExecutionJobIdRouteImport } from './routes/execution-jobs.$executionJobId'
import { Route as ExecutionPlansExecutionPlanIdRouteImport } from './routes/execution-plans.$executionPlanId'
import { Route as FilesFileIdRouteImport } from './routes/files.$fileId'
import { Route as RecommendationsRecommendationIdRouteImport } from './routes/recommendations.$recommendationId'
import { Route as WorkflowExecutionsWorkflowExecutionIdRouteImport } from './routes/workflow-executions.$workflowExecutionId'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows.$workflowId'
import { Route as ConnectorsGoogleCallbackRouteImport } from './routes/connectors.google.callback'
import { Route as WorkflowsWorkflowIdBuilderRouteImport } from './routes/workflows.$workflowId.builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationTemplatesRoute = AutomationTemplatesRouteImport.update({
  id: '/automation-templates',
  path: '/automation-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionJobsRoute = ExecutionJobsRouteImport.update({
  id: '/execution-jobs',
  path: '/execution-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionPlansRoute = ExecutionPlansRouteImport.update({
  id: '/execution-plans',
  path: '/execution-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageConnectionsRoute = StorageConnectionsRouteImport.update({
  id: '/storage-connections',
  path: '/storage-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowExecutionsRoute = WorkflowExecutionsRouteImport.update({
  id: '/workflow-executions',
  path: '/workflow-executions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowPoliciesRoute = WorkflowPoliciesRouteImport.update({
  id: '/workflow-policies',
  path: '/workflow-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)
const ExecutionJobsExecutionJobIdRoute =
  ExecutionJobsExecutionJobIdRouteImport.update({
    id: '/$executionJobId',
    path: '/$executionJobId',
    getParentRoute: () => ExecutionJobsRoute,
  } as any)
const ExecutionPlansExecutionPlanIdRoute =
  ExecutionPlansExecutionPlanIdRouteImport.update({
    id: '/$executionPlanId',
    path: '/$executionPlanId',
    getParentRoute: () => ExecutionPlansRoute,
  } as any)
const FilesFileIdRoute = FilesFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => FilesRoute,
} as any)
const RecommendationsRecommendationIdRoute =
  RecommendationsRecommendationIdRouteImport.update({
    id: '/$recommendationId',
    path: '/$recommendationId',
    getParentRoute: () => RecommendationsRoute,
  } as any)
const WorkflowExecutionsWorkflowExecutionIdRoute =
  WorkflowExecutionsWorkflowExecutionIdRouteImport.update({
    id: '/$workflowExecutionId',
    path: '/$workflowExecutionId',
    getParentRoute: () => WorkflowExecutionsRoute,
  } as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowsRoute,
} as any)
const ConnectorsGoogleCallbackRoute =
  ConnectorsGoogleCallbackRouteImport.update({
    id: '/connectors/google/callback',
    path: '/connectors/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowIdBuilderRoute =
  WorkflowsWorkflowIdBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/automation-templates': typeof AutomationTemplatesRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/execution-jobs': typeof ExecutionJobsRouteWithChildren
  '/execution-plans': typeof ExecutionPlansRouteWithChildren
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workflow-executions': typeof WorkflowExecutionsRouteWithChildren
  '/workflow-policies': typeof WorkflowPoliciesRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/execution-jobs/$executionJobId': typeof ExecutionJobsExecutionJobIdRoute
  '/execution-plans/$executionPlanId': typeof ExecutionPlansExecutionPlanIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/workflow-executions/$workflowExecutionId': typeof WorkflowExecutionsWorkflowExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/workflows/$workflowId/builder': typeof WorkflowsWorkflowIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/automation-templates': typeof AutomationTemplatesRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/execution-jobs': typeof ExecutionJobsRouteWithChildren
  '/execution-plans': typeof ExecutionPlansRouteWithChildren
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workflow-executions': typeof WorkflowExecutionsRouteWithChildren
  '/workflow-policies': typeof WorkflowPoliciesRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/execution-jobs/$executionJobId': typeof ExecutionJobsExecutionJobIdRoute
  '/execution-plans/$executionPlanId': typeof ExecutionPlansExecutionPlanIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/workflow-executions/$workflowExecutionId': typeof WorkflowExecutionsWorkflowExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/workflows/$workflowId/builder': typeof WorkflowsWorkflowIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/automation-templates': typeof AutomationTemplatesRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/execution-jobs': typeof ExecutionJobsRouteWithChildren
  '/execution-plans': typeof ExecutionPlansRouteWithChildren
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRouteWithChildren
  '/scans': typeof ScansRoute
  '/search': typeof SearchRoute
  '/storage-connections': typeof StorageConnectionsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workflow-executions': typeof WorkflowExecutionsRouteWithChildren
  '/workflow-policies': typeof WorkflowPoliciesRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/execution-jobs/$executionJobId': typeof ExecutionJobsExecutionJobIdRoute
  '/execution-plans/$executionPlanId': typeof ExecutionPlansExecutionPlanIdRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/recommendations/$recommendationId': typeof RecommendationsRecommendationIdRoute
  '/workflow-executions/$workflowExecutionId': typeof WorkflowExecutionsWorkflowExecutionIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/connectors/google/callback': typeof ConnectorsGoogleCallbackRoute
  '/workflows/$workflowId/builder': typeof WorkflowsWorkflowIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/automation'
    | '/automation-templates'
    | '/chat'
    | '/dashboard'
    | '/execution-jobs'
    | '/execution-plans'
    | '/files'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/recommendations'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/unauthorized'
    | '/workflow-executions'
    | '/workflow-policies'
    | '/workflows'
    | '/chat/$conversationId'
    | '/execution-jobs/$executionJobId'
    | '/execution-plans/$executionPlanId'
    | '/files/$fileId'
    | '/recommendations/$recommendationId'
    | '/workflow-executions/$workflowExecutionId'
    | '/workflows/$workflowId'
    | '/connectors/google/callback'
    | '/workflows/$workflowId/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/automation'
    | '/automation-templates'
    | '/chat'
    | '/dashboard'
    | '/execution-jobs'
    | '/execution-plans'
    | '/files'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/recommendations'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/unauthorized'
    | '/workflow-executions'
    | '/workflow-policies'
    | '/workflows'
    | '/chat/$conversationId'
    | '/execution-jobs/$executionJobId'
    | '/execution-plans/$executionPlanId'
    | '/files/$fileId'
    | '/recommendations/$recommendationId'
    | '/workflow-executions/$workflowExecutionId'
    | '/workflows/$workflowId'
    | '/connectors/google/callback'
    | '/workflows/$workflowId/builder'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/automation'
    | '/automation-templates'
    | '/chat'
    | '/dashboard'
    | '/execution-jobs'
    | '/execution-plans'
    | '/files'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/profile'
    | '/recommendations'
    | '/scans'
    | '/search'
    | '/storage-connections'
    | '/unauthorized'
    | '/workflow-executions'
    | '/workflow-policies'
    | '/workflows'
    | '/chat/$conversationId'
    | '/execution-jobs/$executionJobId'
    | '/execution-plans/$executionPlanId'
    | '/files/$fileId'
    | '/recommendations/$recommendationId'
    | '/workflow-executions/$workflowExecutionId'
    | '/workflows/$workflowId'
    | '/connectors/google/callback'
    | '/workflows/$workflowId/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationRoute: typeof AutomationRoute
  AutomationTemplatesRoute: typeof AutomationTemplatesRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExecutionJobsRoute: typeof ExecutionJobsRouteWithChildren
  ExecutionPlansRoute: typeof ExecutionPlansRouteWithChildren
  FilesRoute: typeof FilesRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRouteWithChildren
  ScansRoute: typeof ScansRoute
  SearchRoute: typeof SearchRoute
  StorageConnectionsRoute: typeof StorageConnectionsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WorkflowExecutionsRoute: typeof WorkflowExecutionsRouteWithChildren
  WorkflowPoliciesRoute: typeof WorkflowPoliciesRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ConnectorsGoogleCallbackRoute: typeof ConnectorsGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-templates': {
      id: '/automation-templates'
      path: '/automation-templates'
      fullPath: '/automation-templates'
      preLoaderRoute: typeof AutomationTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution-jobs': {
      id: '/execution-jobs'
      path: '/execution-jobs'
      fullPath: '/execution-jobs'
      preLoaderRoute: typeof ExecutionJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution-plans': {
      id: '/execution-plans'
      path: '/execution-plans'
      fullPath: '/execution-plans'
      preLoaderRoute: typeof ExecutionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-connections': {
      id: '/storage-connections'
      path: '/storage-connections'
      fullPath: '/storage-connections'
      preLoaderRoute: typeof StorageConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-executions': {
      id: '/workflow-executions'
      path: '/workflow-executions'
      fullPath: '/workflow-executions'
      preLoaderRoute: typeof WorkflowExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-policies': {
      id: '/workflow-policies'
      path: '/workflow-policies'
      fullPath: '/workflow-policies'
      preLoaderRoute: typeof WorkflowPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/execution-jobs/$executionJobId': {
      id: '/execution-jobs/$executionJobId'
      path: '/$executionJobId'
      fullPath: '/execution-jobs/$executionJobId'
      preLoaderRoute: typeof ExecutionJobsExecutionJobIdRouteImport
      parentRoute: typeof ExecutionJobsRoute
    }
    '/execution-plans/$executionPlanId': {
      id: '/execution-plans/$executionPlanId'
      path: '/$executionPlanId'
      fullPath: '/execution-plans/$executionPlanId'
      preLoaderRoute: typeof ExecutionPlansExecutionPlanIdRouteImport
      parentRoute: typeof ExecutionPlansRoute
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/recommendations/$recommendationId': {
      id: '/recommendations/$recommendationId'
      path: '/$recommendationId'
      fullPath: '/recommendations/$recommendationId'
      preLoaderRoute: typeof RecommendationsRecommendationIdRouteImport
      parentRoute: typeof RecommendationsRoute
    }
    '/workflow-executions/$workflowExecutionId': {
      id: '/workflow-executions/$workflowExecutionId'
      path: '/$workflowExecutionId'
      fullPath: '/workflow-executions/$workflowExecutionId'
      preLoaderRoute: typeof WorkflowExecutionsWorkflowExecutionIdRouteImport
      parentRoute: typeof WorkflowExecutionsRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/connectors/google/callback': {
      id: '/connectors/google/callback'
      path: '/connectors/google/callback'
      fullPath: '/connectors/google/callback'
      preLoaderRoute: typeof ConnectorsGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/builder': {
      id: '/workflows/$workflowId/builder'
      path: '/builder'
      fullPath: '/workflows/$workflowId/builder'
      preLoaderRoute: typeof WorkflowsWorkflowIdBuilderRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ExecutionJobsRouteChildren {
  ExecutionJobsExecutionJobIdRoute: typeof ExecutionJobsExecutionJobIdRoute
}

const ExecutionJobsRouteChildren: ExecutionJobsRouteChildren = {
  ExecutionJobsExecutionJobIdRoute: ExecutionJobsExecutionJobIdRoute,
}

const ExecutionJobsRouteWithChildren = ExecutionJobsRoute._addFileChildren(
  ExecutionJobsRouteChildren,
)

interface ExecutionPlansRouteChildren {
  ExecutionPlansExecutionPlanIdRoute: typeof ExecutionPlansExecutionPlanIdRoute
}

const ExecutionPlansRouteChildren: ExecutionPlansRouteChildren = {
  ExecutionPlansExecutionPlanIdRoute: ExecutionPlansExecutionPlanIdRoute,
}

const ExecutionPlansRouteWithChildren = ExecutionPlansRoute._addFileChildren(
  ExecutionPlansRouteChildren,
)

interface FilesRouteChildren {
  FilesFileIdRoute: typeof FilesFileIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesFileIdRoute: FilesFileIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface RecommendationsRouteChildren {
  RecommendationsRecommendationIdRoute: typeof RecommendationsRecommendationIdRoute
}

const RecommendationsRouteChildren: RecommendationsRouteChildren = {
  RecommendationsRecommendationIdRoute: RecommendationsRecommendationIdRoute,
}

const RecommendationsRouteWithChildren = RecommendationsRoute._addFileChildren(
  RecommendationsRouteChildren,
)

interface WorkflowExecutionsRouteChildren {
  WorkflowExecutionsWorkflowExecutionIdRoute: typeof WorkflowExecutionsWorkflowExecutionIdRoute
}

const WorkflowExecutionsRouteChildren: WorkflowExecutionsRouteChildren = {
  WorkflowExecutionsWorkflowExecutionIdRoute:
    WorkflowExecutionsWorkflowExecutionIdRoute,
}

const WorkflowExecutionsRouteWithChildren =
  WorkflowExecutionsRoute._addFileChildren(WorkflowExecutionsRouteChildren)

interface WorkflowsWorkflowIdRouteChildren {
  WorkflowsWorkflowIdBuilderRoute: typeof WorkflowsWorkflowIdBuilderRoute
}

const WorkflowsWorkflowIdRouteChildren: WorkflowsWorkflowIdRouteChildren = {
  WorkflowsWorkflowIdBuilderRoute: WorkflowsWorkflowIdBuilderRoute,
}

const WorkflowsWorkflowIdRouteWithChildren =
  WorkflowsWorkflowIdRoute._addFileChildren(WorkflowsWorkflowIdRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRouteWithChildren
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRouteWithChildren,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationRoute: AutomationRoute,
  AutomationTemplatesRoute: AutomationTemplatesRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExecutionJobsRoute: ExecutionJobsRouteWithChildren,
  ExecutionPlansRoute: ExecutionPlansRouteWithChildren,
  FilesRoute: FilesRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRouteWithChildren,
  ScansRoute: ScansRoute,
  SearchRoute: SearchRoute,
  StorageConnectionsRoute: StorageConnectionsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WorkflowExecutionsRoute: WorkflowExecutionsRouteWithChildren,
  WorkflowPoliciesRoute: WorkflowPoliciesRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ConnectorsGoogleCallbackRoute: ConnectorsGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
